default_vars:
  dns_domain: ci-demo.aardsoft.fi

networks:
  demo:
    subnets:
      "10.11.12.0/24":
        options:
          - range 10.11.12.150 10.11.12.200
          - option routers 10.11.12.1
          - option ntp-servers 10.11.12.1
          - option domain-name-servers 10.11.12.1
        boot_options:
          pxe:
            - next-server 10.11.12.1

hosts:
  microgw:
    rack_mounted: 0
    type: notebook
    host_vars:
      ansible_host: 127.0.0.1
      ansible_port: 60322
      debug_variables: True
      dhcpd:
        chroot: false
      dhcp_boot: true
    networks:
      enp0s5:
        static: no
        masquerade: both
      enp0s6:
        static: yes
        masquerade: both
        ipv4: 10.11.12.1/24
