netboot:
  pxe_filename: shim.efi
  combustion:
    commands:
      - print_debug_info
    commands_initrd:
      - print_debug_info
      - default_initrd
    commands_noinitrd:
      - default_noinitrd
  os:
    microos_16:
      name: OpenSuSE MicroOS 16
      source: https://mirror.aardsoft.fi/opensuse/tumbleweed/appliances/openSUSE-MicroOS.x86_64-SelfInstall.install.tar
      path: /micro
      linuxefi:
        path: /micro/pxeboot.openSUSE-MicroOS.x86_64-16.0.0.kernel
        args: rd.kiwi.install.pxe rd.kiwi.install.image=tftp://10.11.12.1/micro/openSUSE-MicroOS.x86_64-16.0.0.xz  console=ttyS0,115200 console=tty0 combustion.url=tftp://10.11.12.1/combustion/script combustion.firstboot rd.kiwi.install.pass.bootparam="combustion.url=tftp://10.11.12.1/combustion/script"
      initrdefi:
        path: /micro/pxeboot.openSUSE-MicroOS.x86_64-16.0.0.initrd
    microos_16_arm:
      name: OpenSuSE MicroOS 16 aarch64
      source: https://download-repositories.opensuse.org/download/ports/aarch64/factory/appliances/openSUSE-MicroOS.aarch64-SelfInstall.install.tar
      path: /micro
      linuxefi:
        path: /micro/pxeboot.openSUSE-MicroOS.x86_64-16.0.0.kernel
        args: rd.kiwi.install.pxe rd.kiwi.install.image=tftp://10.11.12.1/micro/openSUSE-MicroOS.x86_64-16.0.0.xz  console=ttyS0,115200 console=tty0 combustion.url=tftp://10.11.12.1/combustion/script combustion.firstboot rd.kiwi.install.pass.bootparam="combustion.url=tftp://10.11.12.1/combustion/script"
      initrdefi:
        path: /micro/pxeboot.openSUSE-MicroOS.x86_64-16.0.0.initrd
    tumbleweed:
      name: OpenSuSE Tumbleweed
      linuxefi:
        path: /tumbleweed/linux
        args: ip=dhcp install=https://mirror.aardsoft.fi/opensuse/tumbleweed/repo/oss/boot/x86_64/loader
        source: https://mirror.aardsoft.fi/opensuse/tumbleweed/repo/oss/boot/x86_64/loader/linux
      initrdefi:
        path: /tumbleweed/initrd
        source: https://mirror.aardsoft.fi/opensuse/tumbleweed/repo/oss/boot/x86_64/loader/initrd
  entries:
    tumbleweed_rescue:
      name: rescue system
      args: rescue=1
      os: tumbleweed
    microos_install_kvm:
      name: kvm install
      args: rd.kiwi.oem.installdevice=/dev/vda
      os: microos_16
